# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nas_name', models.CharField(help_text='NAS Name (or IP address)', max_length=128, unique=True, verbose_name='nas name')),
                ('short_name', models.CharField(max_length=32, verbose_name='short name')),
                ('type', models.CharField(max_length=30, verbose_name='type')),
                ('secret', models.CharField(help_text='Shared Secret', max_length=60, verbose_name='secret')),
                ('ports', models.IntegerField(blank=True, null=True, verbose_name='ports')),
                ('community', models.CharField(blank=True, max_length=50, null=True, verbose_name='community')),
            ],
            options={
                'verbose_name_plural': 'nas',
                'verbose_name': 'nas',
                'db_table': 'nas',
            },
        ),
        migrations.CreateModel(
            name='RadiusAccounting',
            fields=[
                ('rad_acct_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('acct_session_id', models.CharField(max_length=32)),
                ('acct_unique_id', models.CharField(max_length=32)),
                ('user_name', models.CharField(max_length=64, verbose_name='username')),
                ('realm', models.CharField(max_length=64, null=True, verbose_name='realm')),
                ('nas_ip_address', models.CharField(max_length=15)),
                ('nas_port_id', models.CharField(max_length=15, null=True)),
                ('nas_port_type', models.CharField(max_length=32, verbose_name='nas port type')),
                ('acct_start_time', models.DateTimeField(verbose_name='acct start time')),
                ('acct_stop_time', models.DateTimeField(null=True, verbose_name='acct stop time')),
                ('acct_session_time', models.IntegerField(null=True, verbose_name='acct session time')),
                ('acct_authentic', models.CharField(max_length=32, null=True, verbose_name='acct authentic')),
                ('connection_info_start', models.CharField(max_length=50, null=True, verbose_name='connection info start')),
                ('connection_info_stop', models.CharField(max_length=50, null=True, verbose_name='connection info stop')),
                ('acct_input_octets', models.BigIntegerField(null=True, verbose_name='acct input octets')),
                ('acct_output_octets', models.BigIntegerField(null=True, verbose_name='acct output octets')),
                ('callingStationId', models.CharField(max_length=50)),
                ('calledStationId', models.CharField(max_length=50)),
                ('acct_terminate_cause', models.CharField(max_length=32, verbose_name='acct terminate cause')),
                ('service_type', models.CharField(max_length=32, null=True, verbose_name='service type')),
                ('framed_protocol', models.CharField(max_length=32, null=True, verbose_name='framed protocol')),
                ('framed_ip_address', models.CharField(max_length=15)),
                ('acct_start_delay', models.IntegerField(null=True, verbose_name='acct start delay')),
                ('acct_stop_delay', models.IntegerField(null=True, verbose_name='acct stop delay')),
                ('xascend_session_svrkey', models.CharField(max_length=10, null=True, verbose_name='xascend session svrkey')),
            ],
            options={
                'verbose_name_plural': 'radiusaccounting',
                'verbose_name': 'radiusaccounting',
                'db_table': 'radiusaccounting',
            },
        ),
        migrations.CreateModel(
            name='RadiusChecks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64, verbose_name='username')),
                ('value', models.CharField(max_length=40, verbose_name='radiusvalue')),
                ('op', models.CharField(max_length=2, verbose_name='op')),
                ('attribute', models.CharField(max_length=64, verbose_name='attribute')),
            ],
            options={
                'verbose_name_plural': 'radiuschecks',
                'verbose_name': 'radiuschecks',
                'db_table': 'radiuschecks',
            },
        ),
        migrations.CreateModel(
            name='RadiusGroup',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=255, unique=True, verbose_name='groupname')),
                ('priority', models.IntegerField(default=1, verbose_name='priority')),
                ('creation_date', models.DateField(null=True, verbose_name='creation date')),
                ('modification_date', models.DateField(null=True, verbose_name='modification date')),
                ('notes', models.CharField(blank=True, max_length=64, verbose_name='notes')),
            ],
            options={
                'verbose_name_plural': 'radiusgroups',
                'verbose_name': 'radiusgroup',
                'db_table': 'radiusgroup',
            },
        ),
        migrations.CreateModel(
            name='RadiusGroupUsers',
            fields=[
                ('user_name', models.CharField(max_length=64, unique=True, verbose_name='username')),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=255, unique=True, verbose_name='groupname')),
                ('radius_checks', models.ManyToManyField(blank=True, to='django_freeradius.RadiusChecks', verbose_name='radius checks')),
            ],
            options={
                'verbose_name_plural': 'radiusgroupusers',
                'verbose_name': 'radiusgroupusers',
                'db_table': 'radiusgroupusers',
            },
        ),
        migrations.CreateModel(
            name='RadiusReplies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64, verbose_name='username')),
                ('value', models.CharField(max_length=40, verbose_name='value')),
                ('op', models.CharField(max_length=2, verbose_name='op')),
                ('attribute', models.CharField(max_length=64, verbose_name='attribute')),
            ],
            options={
                'verbose_name_plural': 'radiusreplies',
                'verbose_name': 'radiusreplies',
                'db_table': 'radiusreplies',
            },
        ),
        migrations.AddField(
            model_name='radiusgroupusers',
            name='radius_replies',
            field=models.ManyToManyField(blank=True, to='django_freeradius.RadiusReplies', verbose_name='radius replies'),
        ),
    ]
