# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nas_name', models.CharField(help_text='NAS Name (or IP address)', max_length=128, unique=True)),
                ('short_name', models.CharField(max_length=32)),
                ('type', models.CharField(max_length=30)),
                ('secret', models.CharField(help_text='Shared Secret', max_length=60)),
                ('ports', models.IntegerField(blank=True, null=True)),
                ('community', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'nas',
            },
        ),
        migrations.CreateModel(
            name='RadiusAccounting',
            fields=[
                ('rad_acct_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('acct_session_id', models.CharField(max_length=32)),
                ('acct_unique_id', models.CharField(max_length=32)),
                ('user_name', models.CharField(max_length=64)),
                ('realm', models.CharField(max_length=64, null=True)),
                ('nas_ip_address', models.CharField(max_length=15)),
                ('nas_port_id', models.CharField(max_length=15, null=True)),
                ('nas_port_type', models.CharField(max_length=32)),
                ('acct_start_time', models.DateTimeField()),
                ('acct_stop_time', models.DateTimeField(null=True)),
                ('acct_session_time', models.IntegerField(null=True)),
                ('acct_authentic', models.CharField(max_length=32, null=True)),
                ('connection_info_start', models.CharField(max_length=50, null=True)),
                ('connection_info_stop', models.CharField(max_length=50, null=True)),
                ('acct_input_octets', models.BigIntegerField(null=True)),
                ('acct_output_octets', models.BigIntegerField(null=True)),
                ('callingStationId', models.CharField(max_length=50)),
                ('calledStationId', models.CharField(max_length=50)),
                ('acct_terminate_cause', models.CharField(max_length=32)),
                ('service_type', models.CharField(max_length=32, null=True)),
                ('framed_protocol', models.CharField(max_length=32, null=True)),
                ('framed_ip_address', models.CharField(max_length=15)),
                ('acct_start_delay', models.IntegerField(null=True)),
                ('acct_stop_delay', models.IntegerField(null=True)),
                ('xascend_session_svrkey', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'radiusaccounting',
            },
        ),
        migrations.CreateModel(
            name='RadiusChecks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=40)),
                ('op', models.CharField(max_length=2)),
                ('attribute', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'radiuschecks',
            },
        ),
        migrations.CreateModel(
            name='RadiusGroup',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=255, unique=True)),
                ('priority', models.IntegerField(default=1)),
                ('creation_date', models.DateField(null=True)),
                ('modification_date', models.DateField(null=True)),
                ('notes', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'db_table': 'radiusgroup',
            },
        ),
        migrations.CreateModel(
            name='RadiusGroupUsers',
            fields=[
                ('user_name', models.CharField(max_length=64, unique=True)),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=255, unique=True)),
                ('radius_checks', models.ManyToManyField(blank=True, to='django_freeradius.RadiusChecks')),
            ],
            options={
                'db_table': 'radiusgroupusers',
            },
        ),
        migrations.CreateModel(
            name='RadiusReplies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=40)),
                ('op', models.CharField(max_length=2)),
                ('attribute', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'radiusreplies',
            },
        ),
        migrations.AddField(
            model_name='radiusgroupusers',
            name='radius_replies',
            field=models.ManyToManyField(blank=True, to='django_freeradius.RadiusReplies'),
        ),
    ]
