# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_freeradius', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiuscheck',
            name='op',
            field=models.CharField(db_column='op', default='==', max_length=2, verbose_name='operator'),
        ),
        migrations.AlterField(
            model_name='radiuscheck',
            name='value',
            field=models.CharField(db_column='value', max_length=253, verbose_name='radiusvalue'),
        ),
    ]
