# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_freeradius', '0002_auto_20170603_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiuscheck',
            name='op',
            field=models.CharField(choices=[('=', '='), (':=', ':='), ('==', '=='), ('+=', '+='), ('!=', '!='), ('>', '>'), ('>=', '>='), ('<', '<'), ('<=', '<='), ('=~', '=~'), ('!~', '!~'), ('=*', '=*'), ('!*', '!*')], db_column='op', default=':=', max_length=2, verbose_name='operator'),
        ),
        migrations.AlterField(
            model_name='radiusgroupcheck',
            name='op',
            field=models.CharField(choices=[('=', '='), (':=', ':='), ('==', '=='), ('+=', '+='), ('!=', '!='), ('>', '>'), ('>=', '>='), ('<', '<'), ('<=', '<='), ('=~', '=~'), ('!~', '!~'), ('=*', '=*'), ('!*', '!*')], db_column='op', default=':=', max_length=2, verbose_name='operator'),
        ),
        migrations.AlterField(
            model_name='radiusreply',
            name='op',
            field=models.CharField(choices=[('=', '='), (':=', ':='), ('+=', '+=')], db_column='op', default='=', max_length=2, verbose_name='operator'),
        ),
    ]
