# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_freeradius', '0002_radiusaccounting_acct_update_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radiusaccounting',
            old_name='rad_acct_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='radiusaccounting',
            old_name='acct_unique_id',
            new_name='unique_id',
        ),
        migrations.RenameField(
            model_name='radiusaccounting',
            old_name='acct_authentic',
            new_name='authentication',
        ),
        migrations.RenameField(
            model_name='radiusaccounting',
            old_name='acct_input_octets',
            new_name='input_octets',
        ),
        migrations.RenameField(
            model_name='radiusaccounting',
            old_name='acct_output_octets',
            new_name='output_octets',
        ),
        migrations.RenameField(
            model_name='radiusaccounting',
            old_name='acct_session_id',
            new_name='session_id',
        ),
        migrations.RenameField(
            model_name='radiusaccounting',
            old_name='acct_session_time',
            new_name='session_time',
        ),
        migrations.RenameField(
            model_name='radiusaccounting',
            old_name='acct_start_time',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='radiusaccounting',
            old_name='acct_stop_time',
            new_name='stop_time',
        ),
        migrations.RenameField(
            model_name='radiusaccounting',
            old_name='acct_terminate_cause',
            new_name='terminate_cause',
        ),
        migrations.RenameField(
            model_name='radiusaccounting',
            old_name='acct_update_time',
            new_name='update_time',
        ),
        migrations.RemoveField(
            model_name='radiusaccounting',
            name='acct_start_delay',
        ),
        migrations.RemoveField(
            model_name='radiusaccounting',
            name='acct_stop_delay',
        ),
        migrations.RemoveField(
            model_name='radiusaccounting',
            name='xascend_session_svrkey',
        ),
        migrations.RemoveField(
            model_name='radiusaccounting',
            name='created',
        ),
        migrations.RemoveField(
            model_name='radiusaccounting',
            name='modified',
        ),
        migrations.AddField(
            model_name='radiusaccounting',
            name='interval',
            field=models.IntegerField(blank=True, db_column='acctinterval', null=True, verbose_name='interval'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='called_station_id',
            field=models.CharField(blank=True, db_column='callingstationid', null=True, max_length=50, verbose_name='called station ID'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='calling_station_id',
            field=models.CharField(blank=True, db_column='calledstationid', null=True, max_length=50, verbose_name='calling station ID'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='connection_info_start',
            field=models.CharField(blank=True, db_column='connectinfo_start', max_length=50, null=True, verbose_name='connection info start'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='connection_info_stop',
            field=models.CharField(blank=True, db_column='connectinfo_stop', max_length=50, null=True, verbose_name='connection info stop'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='framed_ip_address',
            field=models.CharField(blank=True, db_column='framedipaddress', db_index=False, max_length=15, verbose_name='framed IP address'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='framed_protocol',
            field=models.CharField(blank=True, db_column='framedprotocol', max_length=32, null=True, verbose_name='framed protocol'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='groupname',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='group name'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='nas_port_id',
            field=models.CharField(blank=True, db_column='nasportid', max_length=15, null=True, verbose_name='NAS port ID'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='nas_port_type',
            field=models.CharField(blank=True, db_column='nasporttype', max_length=32, null=True, verbose_name='NAS port type'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='id',
            field=models.BigAutoField(db_column='radacctid', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='realm',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='realm'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='service_type',
            field=models.CharField(blank=True, db_column='servicetype', max_length=32, null=True, verbose_name='service type'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='nas_ip_address',
            field=models.GenericIPAddressField(db_column='nasipaddress', db_index=False, verbose_name='NAS IP address'),
        )
    ]
