# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_freeradius', '0002_auto_20170706_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radiusgroup',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='radiusgroup',
            name='modification_date',
        ),
    ]
