# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_freeradius', '0003_auto_20170706_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radiuspostauthentication',
            name='created',
        ),
        migrations.RemoveField(
            model_name='radiuspostauthentication',
            name='modified',
        ),
    ]
