# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_freeradius', '0003_auto_20170727_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiusaccounting',
            name='authentication',
            field=models.CharField(blank=True, db_column='acctauthentic', max_length=32, null=True, verbose_name='authentication'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='framed_ip_address',
            field=models.GenericIPAddressField(db_column='framedipaddress', db_index=True, null=True, blank=True, verbose_name='framed IP address'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='input_octets',
            field=models.BigIntegerField(blank=True, db_column='acctinputoctets', null=True, verbose_name='input octets'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='nas_ip_address',
            field=models.GenericIPAddressField(db_column='nasipaddress', db_index=True, verbose_name='NAS IP address'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='output_octets',
            field=models.BigIntegerField(blank=True, db_column='acctoutputoctets', null=True, verbose_name='output octets'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='session_id',
            field=models.CharField(db_column='acctsessionid', db_index=True, max_length=64, verbose_name='session ID'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='session_time',
            field=models.PositiveIntegerField(blank=True, db_column='acctsessiontime', null=True, verbose_name='session time'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='start_time',
            field=models.DateTimeField(blank=True, db_column='acctstarttime', db_index=True, null=True, verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='stop_time',
            field=models.DateTimeField(blank=True, db_column='acctstoptime', db_index=True, null=True, verbose_name='stop time'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='terminate_cause',
            field=models.CharField(blank=True, db_column='acctterminatecause', null=True, max_length=32, verbose_name='termination cause'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='update_time',
            field=models.DateTimeField(blank=True, db_column='acctupdatetime', null=True, verbose_name='update time'),
        ),
    ]
