# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_freeradius', '0004_auto_20170711_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radiusaccounting',
            old_name='calledStationId',
            new_name='called_station_id',
        ),
        migrations.RenameField(
            model_name='radiusaccounting',
            old_name='callingStationId',
            new_name='calling_station_id',
        ),
    ]
