# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 16:16
from __future__ import unicode_literals

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_freeradius', '0004_auto_20170614_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='nas',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='nas',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='radiusaccounting',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='radiusaccounting',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='radiuscheck',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='radiuscheck',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='radiusgroup',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='radiusgroup',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='radiusgroupcheck',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='radiusgroupcheck',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='radiusgroupreply',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='radiusgroupreply',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='radiusgroupusers',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='radiusgroupusers',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='radiuspostauthentication',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='radiuspostauthentication',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='radiusreply',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='radiusreply',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='radiususergroup',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='radiususergroup',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='nas',
            name='community',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='community'),
        ),
        migrations.AlterField(
            model_name='nas',
            name='description',
            field=models.CharField(max_length=200, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='nas',
            name='ports',
            field=models.IntegerField(blank=True, null=True, verbose_name='ports'),
        ),
        migrations.AlterField(
            model_name='nas',
            name='secret',
            field=models.CharField(help_text='Shared Secret', max_length=60, verbose_name='secret'),
        ),
        migrations.AlterField(
            model_name='nas',
            name='server',
            field=models.CharField(max_length=64, null=True, verbose_name='server'),
        ),
        migrations.AlterField(
            model_name='nas',
            name='type',
            field=models.CharField(max_length=30, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='realm',
            field=models.CharField(max_length=64, null=True, verbose_name='realm'),
        ),
        migrations.AlterField(
            model_name='radiuscheck',
            name='attribute',
            field=models.CharField(max_length=64, verbose_name='attribute'),
        ),
        migrations.AlterField(
            model_name='radiuscheck',
            name='op',
            field=models.CharField(choices=[('=', '='), (':=', ':='), ('==', '=='), ('+=', '+='), ('!=', '!='), ('>', '>'), ('>=', '>='), ('<', '<'), ('<=', '<='), ('=~', '=~'), ('!~', '!~'), ('=*', '=*'), ('!*', '!*')], default=':=', max_length=2, verbose_name='operator'),
        ),
        migrations.AlterField(
            model_name='radiuscheck',
            name='value',
            field=models.CharField(max_length=253, verbose_name='radiusvalue'),
        ),
        migrations.AlterField(
            model_name='radiusgroup',
            name='notes',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='radiusgroup',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='radiusgroupcheck',
            name='attribute',
            field=models.CharField(max_length=64, verbose_name='attribute'),
        ),
        migrations.AlterField(
            model_name='radiusgroupcheck',
            name='op',
            field=models.CharField(choices=[('=', '='), (':=', ':='), ('==', '=='), ('+=', '+='), ('!=', '!='), ('>', '>'), ('>=', '>='), ('<', '<'), ('<=', '<='), ('=~', '=~'), ('!~', '!~'), ('=*', '=*'), ('!*', '!*')], default=':=', max_length=2, verbose_name='operator'),
        ),
        migrations.AlterField(
            model_name='radiusgroupcheck',
            name='value',
            field=models.CharField(max_length=253, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='radiusgroupreply',
            name='attribute',
            field=models.CharField(max_length=64, verbose_name='attribute'),
        ),
        migrations.AlterField(
            model_name='radiusgroupreply',
            name='op',
            field=models.CharField(choices=[('=', '='), (':=', ':='), ('+=', '+=')], default='=', max_length=2, verbose_name='operator'),
        ),
        migrations.AlterField(
            model_name='radiusgroupreply',
            name='value',
            field=models.CharField(max_length=253, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='radiuspostauthentication',
            name='reply',
            field=models.CharField(max_length=32, verbose_name='reply'),
        ),
        migrations.AlterField(
            model_name='radiusreply',
            name='attribute',
            field=models.CharField(max_length=64, verbose_name='attribute'),
        ),
        migrations.AlterField(
            model_name='radiusreply',
            name='op',
            field=models.CharField(choices=[('=', '='), (':=', ':='), ('+=', '+=')], default='=', max_length=2, verbose_name='operator'),
        ),
        migrations.AlterField(
            model_name='radiusreply',
            name='value',
            field=models.CharField(max_length=253, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='radiususergroup',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='priority'),
        ),
    ]
