# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_freeradius', '0004_auto_20170727_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiusaccounting',
            name='calling_station_id',
            field=models.CharField(blank=True, db_column='callingstationid2', max_length=50, null=True, verbose_name='calling station ID'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='called_station_id',
            field=models.CharField(blank=True, db_column='calledstationid', max_length=50, null=True, verbose_name='called station ID'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='calling_station_id',
            field=models.CharField(blank=True, db_column='callingstationid', max_length=50, null=True, verbose_name='calling station ID'),
        ),
    ]
