# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_freeradius', '0005_auto_20170726_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radiuspostauthentication',
            old_name='user_name',
            new_name='username',
        ),
    ]
