# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_freeradius', '0005_auto_20170617_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nas',
            options={},
        ),
        migrations.AlterModelOptions(
            name='radiusaccounting',
            options={},
        ),
        migrations.AlterModelOptions(
            name='radiuscheck',
            options={},
        ),
        migrations.AlterModelOptions(
            name='radiusgroup',
            options={},
        ),
        migrations.AlterModelOptions(
            name='radiusgroupcheck',
            options={},
        ),
        migrations.AlterModelOptions(
            name='radiusgroupreply',
            options={},
        ),
        migrations.AlterModelOptions(
            name='radiusgroupusers',
            options={},
        ),
        migrations.AlterModelOptions(
            name='radiuspostauthentication',
            options={},
        ),
        migrations.AlterModelOptions(
            name='radiusreply',
            options={},
        ),
        migrations.AlterModelOptions(
            name='radiususergroup',
            options={},
        ),
        migrations.AlterModelTable(
            name='nas',
            table=None,
        ),
        migrations.AlterModelTable(
            name='radiusaccounting',
            table=None,
        ),
        migrations.AlterModelTable(
            name='radiuscheck',
            table=None,
        ),
        migrations.AlterModelTable(
            name='radiusgroup',
            table=None,
        ),
        migrations.AlterModelTable(
            name='radiusgroupcheck',
            table=None,
        ),
        migrations.AlterModelTable(
            name='radiusgroupreply',
            table=None,
        ),
        migrations.AlterModelTable(
            name='radiusgroupusers',
            table=None,
        ),
        migrations.AlterModelTable(
            name='radiuspostauthentication',
            table=None,
        ),
        migrations.AlterModelTable(
            name='radiusreply',
            table=None,
        ),
        migrations.AlterModelTable(
            name='radiususergroup',
            table=None,
        ),
    ]
