# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_freeradius', '0006_auto_20170617_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nas',
            options={'verbose_name': 'nas', 'verbose_name_plural': 'nas'},
        ),
        migrations.AlterModelOptions(
            name='radiusaccounting',
            options={'verbose_name': 'accounting', 'verbose_name_plural': 'accounting'},
        ),
        migrations.AlterModelOptions(
            name='radiuscheck',
            options={'verbose_name': 'radiuscheck', 'verbose_name_plural': 'radiuschecks'},
        ),
        migrations.AlterModelOptions(
            name='radiusgroup',
            options={'verbose_name': 'radiusgroup', 'verbose_name_plural': 'radiusgroups'},
        ),
        migrations.AlterModelOptions(
            name='radiusgroupcheck',
            options={'verbose_name': 'radiusgroupcheck', 'verbose_name_plural': 'radiusgroupcheck'},
        ),
        migrations.AlterModelOptions(
            name='radiusgroupreply',
            options={'verbose_name': 'radiusgroupreply', 'verbose_name_plural': 'radiusgroupreplies'},
        ),
        migrations.AlterModelOptions(
            name='radiusgroupusers',
            options={'verbose_name': 'radiusgroupusers', 'verbose_name_plural': 'radiusgroupusers'},
        ),
        migrations.AlterModelOptions(
            name='radiuspostauthentication',
            options={'verbose_name': 'radiuspostauthentication', 'verbose_name_plural': 'radiuspostauthentication'},
        ),
        migrations.AlterModelOptions(
            name='radiusreply',
            options={'verbose_name': 'radiusreply', 'verbose_name_plural': 'radiusreplies'},
        ),
        migrations.AlterModelOptions(
            name='radiususergroup',
            options={'verbose_name': 'radiususergroup', 'verbose_name_plural': 'radiususergroup'},
        ),
        migrations.AlterModelTable(
            name='nas',
            table='nas',
        ),
        migrations.AlterModelTable(
            name='radiusaccounting',
            table='radacct',
        ),
        migrations.AlterModelTable(
            name='radiuscheck',
            table='radcheck',
        ),
        migrations.AlterModelTable(
            name='radiusgroup',
            table='radiusgroup',
        ),
        migrations.AlterModelTable(
            name='radiusgroupcheck',
            table='radgroupcheck',
        ),
        migrations.AlterModelTable(
            name='radiusgroupreply',
            table='radgroupreply',
        ),
        migrations.AlterModelTable(
            name='radiusgroupusers',
            table='radiusgroupusers',
        ),
        migrations.AlterModelTable(
            name='radiuspostauthentication',
            table='radpostauth',
        ),
        migrations.AlterModelTable(
            name='radiusreply',
            table='radreply',
        ),
        migrations.AlterModelTable(
            name='radiususergroup',
            table='radusergroup',
        ),
    ]
