# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_freeradius', '0009_radiuscheck_expires'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radiuscheck',
            old_name='expires',
            new_name='valid_until',
        ),
    ]
