# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_freeradius', '0010_auto_20171107_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiuscheck',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
