# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_freeradius', '0013_auto_20171211_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radiuscheck',
            old_name='note',
            new_name='notes',
        ),
        migrations.AlterField(
            model_name='radiuscheck',
            name='attribute',
            field=models.CharField(blank=True, choices=[('Cleartext-Password', 'Cleartext-Password'), ('NT-Password', 'NT-Password'), ('LM-Password', 'LM-Password'), ('MD5-Password', 'MD5-Password'), ('SMD5-Password', 'SMD5-Password'), ('SSHA-Password', 'SSHA-Password'), ('Crypt-Password', 'Crypt-Password')], default='NT-Password', max_length=64, verbose_name='attribute'),
        ),
    ]
