# Generated by Django 2.0.5 on 2018-05-21 09:34

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_freeradius', '0014_auto_20171226_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiusBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='expiration time')),
                ('users', models.ManyToManyField(related_name='radius_batch', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'db_table': 'radbatch',
                'verbose_name_plural': 'radius batches',
                'verbose_name': 'radius batch',
                'swappable': 'DJANGO_FREERADIUS_RADIUSBATCH_MODEL',
            },
        ),
    ]
