# Generated by Django 2.0.5 on 2018-07-08 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_freeradius', '0019_auto_20180705_1745'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RadiusGroup',
        ),
        migrations.RemoveField(
            model_name='radiusgroupusers',
            name='radius_check',
        ),
        migrations.RemoveField(
            model_name='radiusgroupusers',
            name='radius_reply',
        ),
        migrations.AlterField(
            model_name='radiususerprofile',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.DJANGO_FREERADIUS_RADIUSPROFILE_MODEL),
        ),
        migrations.DeleteModel(
            name='RadiusGroupUsers',
        ),
    ]
