# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_radius', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nas',
            options={'verbose_name': 'NAS', 'verbose_name_plural': 'NAS'},
        ),
        migrations.AlterModelOptions(
            name='radiuscheck',
            options={'verbose_name': 'radius check', 'verbose_name_plural': 'radius checks'},
        ),
        migrations.AlterModelOptions(
            name='radiusgroup',
            options={'verbose_name': 'radius group', 'verbose_name_plural': 'radius groups'},
        ),
        migrations.AlterModelOptions(
            name='radiusgroupcheck',
            options={'verbose_name': 'radius group check', 'verbose_name_plural': 'radius group checks'},
        ),
        migrations.AlterModelOptions(
            name='radiusgroupreply',
            options={'verbose_name': 'radius group reply', 'verbose_name_plural': 'radius group replies'},
        ),
        migrations.AlterModelOptions(
            name='radiusgroupusers',
            options={'verbose_name': 'radius group users', 'verbose_name_plural': 'radius group users'},
        ),
        migrations.AlterModelOptions(
            name='radiuspostauthentication',
            options={'verbose_name': 'radius post authentication log', 'verbose_name_plural': 'radius post authentication logs'},
        ),
        migrations.AlterModelOptions(
            name='radiusreply',
            options={'verbose_name': 'radius reply', 'verbose_name_plural': 'radius replies'},
        ),
        migrations.AlterModelOptions(
            name='radiususergroup',
            options={'verbose_name': 'radius user group association', 'verbose_name_plural': 'radius user group associations'},
        ),
        migrations.RemoveField(
            model_name='radiusgroup',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='radiusgroup',
            name='modification_date',
        ),
        migrations.RemoveField(
            model_name='radiuspostauthentication',
            name='created',
        ),
        migrations.RemoveField(
            model_name='radiuspostauthentication',
            name='modified',
        ),
        migrations.AlterField(
            model_name='nas',
            name='nas_name',
            field=models.CharField(db_column='nasname', db_index=True, help_text='NAS Name (or IP address)', max_length=128, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='acct_authentic',
            field=models.CharField(db_column='acctauthentic', max_length=32, null=True, verbose_name='Accounting authentication'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='acct_input_octets',
            field=models.BigIntegerField(db_column='acctinputoctets', null=True, verbose_name='accounting input octets'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='acct_output_octets',
            field=models.BigIntegerField(db_column='acctoutputoctets', null=True, verbose_name='accounting output octets'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='acct_session_id',
            field=models.CharField(db_column='acctsessionid', db_index=True, max_length=64, verbose_name='accounting session ID'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='acct_session_time',
            field=models.IntegerField(db_column='acctsessiontime', db_index=True, null=True, verbose_name='Accounting session time'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='acct_start_delay',
            field=models.IntegerField(db_column='acctstartdelay', null=True, verbose_name='accounting start delay'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='acct_start_time',
            field=models.DateTimeField(db_column='acctstarttime', db_index=True, verbose_name='Accounting start time'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='acct_stop_delay',
            field=models.IntegerField(db_column='acctstopdelay', null=True, verbose_name='accounting stop delay'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='acct_stop_time',
            field=models.DateTimeField(db_column='acctstoptime', db_index=True, null=True, verbose_name='Accounting stop time'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='acct_terminate_cause',
            field=models.CharField(db_column='acctterminatecause', max_length=32, verbose_name='accounting termination cause'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='acct_unique_id',
            field=models.CharField(db_column='acctuniqueid', max_length=32, unique=True, verbose_name='accounting unique ID'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='calledStationId',
            field=models.CharField(db_column='callingstationid', max_length=50, verbose_name='called station ID'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='callingStationId',
            field=models.CharField(db_column='calledstationid', max_length=50, verbose_name='calling station ID'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='framed_ip_address',
            field=models.CharField(db_column='framedipaddress', db_index=True, max_length=15, verbose_name='framed IP address'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='group_name',
            field=models.CharField(db_column='groupname', max_length=64, verbose_name='group name'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='nas_ip_address',
            field=models.CharField(db_column='nasipaddress', db_index=True, max_length=15, verbose_name='NAS IP address'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='nas_port_id',
            field=models.CharField(db_column='nasportid', max_length=15, null=True, verbose_name='NAS port ID'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='nas_port_type',
            field=models.CharField(db_column='nasporttype', max_length=32, verbose_name='NAS port type'),
        ),
        migrations.AlterField(
            model_name='radiusaccounting',
            name='rad_acct_id',
            field=models.BigIntegerField(db_column='radacctid', primary_key=True, serialize=False, verbose_name='RADIUS accounting ID'),
        ),
        migrations.AlterField(
            model_name='radiuscheck',
            name='value',
            field=models.CharField(max_length=253, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='radiusgroup',
            name='group_name',
            field=models.CharField(db_column='groupname', db_index=True, max_length=255, unique=True, verbose_name='group name'),
        ),
        migrations.AlterField(
            model_name='radiusgroupcheck',
            name='group_name',
            field=models.CharField(db_column='groupname', db_index=True, max_length=64, verbose_name='group name'),
        ),
        migrations.AlterField(
            model_name='radiusgroupreply',
            name='group_name',
            field=models.CharField(db_column='groupname', db_index=True, max_length=64, verbose_name='group name'),
        ),
        migrations.AlterField(
            model_name='radiusgroupusers',
            name='group_name',
            field=models.CharField(db_column='groupname', max_length=255, unique=True, verbose_name='group name'),
        ),
        migrations.AlterField(
            model_name='radiususergroup',
            name='group_name',
            field=models.CharField(db_column='groupname', max_length=64, verbose_name='group name'),
        ),
    ]
