# Generated by Django 2.0.5 on 2018-07-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_radius', '0002_radiususerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiuscheck',
            name='attribute',
            field=models.CharField(blank=True, choices=[('Cleartext-Password', 'Cleartext-Password'), ('NT-Password', 'NT-Password'), ('LM-Password', 'LM-Password'), ('MD5-Password', 'MD5-Password'), ('SMD5-Password', 'SMD5-Password'), ('SSHA-Password', 'SSHA-Password'), ('Crypt-Password', 'Crypt-Password'), ('Max-Daily-Session', 'Max-Daily-Session'), ('Max-All-Session', 'Max-All-Session'), ('Max-Daily-Session-Limit', 'Max-Daily-Session-Limit')], default='NT-Password', max_length=64, verbose_name='attribute'),
        ),
    ]
